name = "SciPhiTools"
uuid = "3f46b579-65ac-4d26-b0f7-295ab1cc19bf"
repo = "https://github.com/AwesomeQuest/SciPhiTools.git"
description = "A registry to store my science projects"

[packages]
52ec9b4c-74eb-4bfd-98fc-9000c6dcf858 = { name = "testbluetooth", path = "T/testbluetooth" }
9c2e59a9-ddd1-4208-978e-ca78fec45363 = { name = "KeithleyPico", path = "K/KeithleyPico" }
c43e3543-e659-46d0-a341-79c7b8740d4a = { name = "SimpleBLE", path = "S/SimpleBLE" }
